SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `server` 
DROP FOREIGN KEY `fk_server_cgnode`;

ALTER TABLE `server` 
DROP INDEX `fk_server_cgnode_idx` ;

DROP TABLE IF EXISTS `cgnode` ;

DROP TABLE IF EXISTS `cg_treepath` ;

DROP TABLE IF EXISTS `adj_list` ;

INSERT INTO db_version (version) VALUES(5);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
