-- MySQL Workbench Synchronization
-- Generated: 2014-12-11 17:44
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Aleksandr Kuzminsky

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `volume` 
DROP FOREIGN KEY `fk_volume_storage`;

ALTER TABLE `volume` 
ADD CONSTRAINT `fk_volume_storage`
  FOREIGN KEY (`storage_id`)
  REFERENCES `storage` (`storage_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

INSERT INTO db_version (version) VALUES(28);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
