SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `invitation` (
	  `invitation_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	  `invitation_code` CHAR(32) NULL DEFAULT NULL,
	  `redeemed_at` TIMESTAMP NULL DEFAULT NULL,
	  `comment` TEXT NULL DEFAULT NULL,
	  PRIMARY KEY (`invitation_id`))
	ENGINE = InnoDB
	DEFAULT CHARACTER SET = latin1
	COLLATE = latin1_swedish_ci;


	SET SQL_MODE=@OLD_SQL_MODE;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
	SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO db_version (version) VALUES(2);
